### ISSUE TITLE
Installation script todo and fixes

### ISSUE THREAD

**Issue by JohannesKahl** [Hombremaledicto/be.shell#1]
- [x] Implementing a lazy --noconfirm
- [ ] Better positional parameters handling
- [ ] Diff for scripts and menus 
- [ ] "Rollback" :  install a preset from an archive created with the backup function
- [ ] Check for new commits eventually
